#!/usr/bin/env node
import fs from 'fs';

const typeMap = {
  fix: '修复',
  feat: '新增',
  refactor: '重构',
  test: '测试',
  perf: '性能优化',
  style: '格式调整',
  ci: 'CI/CD',
  docs: '文档',
  chore: '例行维护',
  build: '构建',
};

const scopeMap = {
  translation: '翻译',
  messages: '消息',
  'api-keys': 'API密钥',
  docker: 'Docker',
  tls: 'TLS',
  responses: '响应',
  cors: 'CORS',
  security: '安全',
  auth: '鉴权',
  quota: '配额',
  server: '服务端',
  electron: 'Electron',
  scripts: '脚本',
  build: '构建',
  release: '发布',
  smoke: '冒烟测试',
  cache: '缓存',
  proxy: '代理',
  diag: '诊断',
  web: '前端',
  version: '版本',
};

const vocabulary = [
  ['bug fixes and improvements', '缺陷修复与体验改进'],
  ['bug fix and improvements', '缺陷修复与体验改进'],
  ['bug fixes', '缺陷修复'],
  ['bug fix', '缺陷修复'],
  ['initial release', '初始版本发布'],
  ['client-side', '客户端侧'],
  ['corporate ssl inspection', '企业级 SSL 检查'],
  ['os certificate store', '操作系统证书库'],
  ['model-suffix', '模型后缀'],
  ['model suffix', '模型后缀'],
  ['response streaming', '响应流式化'],
  ['parallel tool_use blocks', '并行工具调用块'],
  ['parallel tool use', '并行工具调用'],
  ['wire protocol', '传输协议'],
  ['custom native api key', '自定义原生 API 密钥'],
  ['api key', 'API 密钥'],
  ['api keys', 'API 密钥'],
  ['count tokens', '计词/统计 Token'],
  ['token count', 'Token 计数'],
  ['count token', '计词/统计 Token'],
  ['update checker', '更新检查器'],
  ['role tests', '角色测试'],
  ['line endings', '行尾换行符'],
  ['message roles', '消息角色'],
  ['uname -m', 'uname -m'],
  ['entrypoint', '入口脚本'],
  ['auto-detect', '自动检测'],
  ['auto detect', '自动检测'],
  ['backfill output', '回填输出'],
  ['middleware handler', '中间件处理器'],
  ['middleware', '中间件'],
  ['environment variable', '环境变量'],
  ['server config', '服务端配置'],
  ['harden affinity', '加固会话亲和性'],
  ['harden dev promotion', '加固开发合并'],
  ['code audit', '代码审计'],
  ['critical/high defects', '严重/高危缺陷'],
  ['critical defects', '严重缺陷'],
  ['high defects', '高危缺陷'],
  ['credit balance', '额度余额'],
  ['pool overview', '账号池概览'],
  ['billing-header', '计费请求头'],
  ['billing header', '计费请求头'],
  ['rotation variants', '轮转变体'],
  ['error logs', '错误日志'],
  ['error log', '错误日志'],
  ['anthropic defaults', 'Anthropic 默认值'],
  ['input_tokens inflation', '输入 Token 膨胀'],
  ['input token inflation', '输入 Token 膨胀'],
  ['messages translation', '消息翻译'],
  ['host binding', '主机绑定'],
  ['loopback origin', '本地回环源'],
  ['loopback origins', '本地回环源'],
  ['loopback', '本地回环'],
  ['read pages', 'Read 工具页面'],
  ['read tool', 'Read 工具'],
  ['manual refresh', '手动刷新'],
  ['refresh button', '刷新按钮'],
  ['preflight requests', '预检请求'],
  ['preflight request', '预检请求'],
  ['embeddings support', '向量嵌入支持'],
  ['embedding support', '向量嵌入支持'],
  ['runtime api keys', '运行时 API 密钥'],
  ['runtime api key', '运行时 API 密钥'],
  ['cockpit account transfer', 'Cockpit 账号转移'],
  ['compatibility', '兼容性'],
  ['egress details', '出口详情'],
  ['client replays', '客户端重放'],
  ['client replay', '客户端重放'],
  ['resume-not-applicable', '恢复不适用'],
  ['missing_tool_calls', '缺失工具调用'],
  ['missing-tool-call', '缺失工具调用'],
  ['replay guard', '重放防护'],
  ['poisoned cookie', '污染的 Cookie'],
  ['cloudflare cookie', 'Cloudflare Cookie'],
  ['function call ids', '函数调用 ID'],
  ['function call id', '函数调用 ID'],
  ['stable notes', '稳定版日志'],
  ['dev promotion history', '开发合并历史'],
  ['dev promotion', '开发合并'],
  ['packaged smoke timeout', '打包打包冒烟超时'],
  ['smoke timeout', '冒烟测试超时'],
  ['smoke test', '冒烟测试'],
  ['model alias', '模型别名'],
  ['model aliases', '模型别名'],
  ['stream fixes', '流式修复'],
  ['lockfile sources', 'Lockfile 源'],
  ['official npm registry', '官方 NPM 源'],
  ['fingerprint state', '指纹状态'],
  ['fingerprint yaml', '指纹 yaml'],
  ['request diagnostics', '请求诊断'],
  ['diagnostics logging', '诊断日志记录'],
  ['diagnostics log', '诊断日志'],
  ['usage logging', '使用日志记录'],
  ['usage log', '使用日志'],
  ['package boundary', '包边界'],
  ['non-streaming', '非流式'],
  ['success release', '成功发布'],
  ['codex api error', 'Codex API 错误'],
  ['failure handling', '失败处理'],
  ['exhaustion handling', '耗尽处理'],
  ['error planning', '错误规划'],
  ['affinity recording', '亲和性记录'],
  ['premature close', '提前关闭'],
  ['empty response retry', '空响应重试'],
  ['retry transition', '重试状态过渡'],
  ['retry recovery', '重试恢复'],
  ['fallback account retry', '备用账号重试'],
  ['implicit resume lifecycle', '隐式恢复生命周期'],
  ['implicit resume', '隐式恢复'],
  ['session context', '会话上下文'],
  ['upstream attempt', '上游尝试'],
  ['request preparation', '请求准备'],
  ['request state', '请求状态'],
  ['fallback retry planning', '备用重试规划'],
  ['stream response', '流式响应'],
  ['stream tracing', '流式追踪'],
  ['egress logging', '出口日志'],
  ['build scripts', '构建脚本'],
  ['build script', '构建脚本'],
  ['debug dump', '调试转储'],
  ['websocket context', 'WebSocket 上下文'],
  ['stagger helper', '交错发送助手'],
  ['rate-limit application', '速率限制应用'],
  ['error response formatting', '错误响应格式化'],
  ['streaming handler', '流式处理器'],
  ['session helpers', '会话助手'],
  ['session helper', '会话助手'],
  ['direct request handler', '直连请求处理器'],
  ['direct request', '直连请求'],
  ['shared types', '共享类型'],
  ['format adapters', '格式适配器'],
  ['format adapter', '格式适配器'],
  ['proxy handlers', '代理处理器'],
  ['proxy handler', '代理处理器'],
  ['stream-close events', '流关闭事件'],
  ['stream-close event', '流关闭事件'],
  ['audit log', '审计日志'],
  ['chat requests', '聊天请求'],
  ['chat request', '聊天请求'],
  ['mobile logs overflow', '移动端日志溢出'],
  ['dashboard design tokens', '仪表盘设计 Token'],
  ['dashboard', '仪表盘'],
  ['corrupt accounts.json', '损坏的 accounts.json'],
  ['corrupt accounts', '损坏的账号'],
  ['quarantine', '隔离'],
  ['api routes', 'API 路由'],
  ['api route', 'API 路由'],
  ['cors middleware', 'CORS 中间件'],
  ['implicit resume chains', '隐式恢复链'],
  ['implicit resume chain', '隐式恢复链'],
  ['rate_limit_until', 'rate_limit_until'],
  ['cachedquota', '缓存配额'],
  ['single truth', '单一数据源'],
  ['usage history snapshots', '使用历史快照'],
  ['usage history snapshot', '使用历史快照'],
  ['debug-dump', '调试转储'],
  ['upstream request', '上游请求'],
  ['upstream response', '上游响应'],
  ['bind errors', '绑定错误'],
  ['bind error', '绑定错误'],
  ['startserver', '启动服务端'],
  ['autoupdate', '自动更新'],
  ['update popup', '更新弹窗'],
  ['renderer error capture', '渲染器错误捕获'],
  ['errors tab', '错误选项卡'],
  ['header badge', '头部徽章'],
  ['local error-log', '本地错误日志'],
  ['local error log', '本地错误日志'],
  ['uncaught capture', '未捕获捕获'],
  ['admin api', '管理端 API'],
  ['bundled ws runtime', '打包的 ws 运行时'],
  ['npm registry', 'NPM 源'],
  ['mac x64 packaged smoke', 'Mac x64 打包冒烟测试'],
  ['serve() bind race', 'serve() 绑定竞争'],
  ['draft release', 'Release 草稿'],
  ['manual upload step', '手动上传步骤'],
  ['manual upload', '手动上传'],
  ['smoke timeout', '冒烟超时'],
  ['es-build', 'esbuild'],
  ['esbuild', 'esbuild'],
  ['prepare pack', '准备打包'],
  ['auto-updater', '自动更新器'],
  ['auto updater', '自动更新器'],
  ['prompt cache key', '提示词缓存键'],
  ['prompt cache', '提示词缓存'],
  ['stream failure events', '流失败事件'],
  ['stream failure event', '流失败事件'],
  ['premature response stream', '提前结束的响应流'],
  ['response stream', '响应流'],
  ['reset windows', '重置窗口'],
  ['reset window', '重置窗口'],
  ['quota cache', '配额缓存'],
  ['model suffix service tier', '模型后缀服务层'],
  ['model suffix', '模型后缀'],
  ['update status settings', '更新状态设置'],
  ['update status', '更新状态'],
  ['bridge concurrency', '桥接并发'],
  ['agent bridge', '智能体桥接'],
  ['unlimited usage history', '无限使用历史'],
  ['usage history', '使用历史'],
  ['update popup preference', '更新弹窗偏好设置'],
  ['popup preference', '弹窗偏好设置'],
  ['claude code model aliases', 'Claude Code 模型别名'],
  ['claude code', 'Claude Code'],
  ['model alias', '模型别名'],
  ['model aliases', '模型别名'],
  ['official codex app server bridge', '官方 Codex App 服务端桥接'],
  ['codex app server bridge', 'Codex App 服务端桥接'],
  ['codex app server', 'Codex App 服务端'],
  ['token metadata', 'Token 元数据'],
  ['quota skip', '配额跳过'],
  ['api key routes', 'API 密钥路由'],
  ['api key route', 'API 密钥路由'],
  ['global proxy', '全局代理'],
  ['ws fallback', 'WS 回退'],
  ['websocket fallback', 'WebSocket 回退'],
  ['codex review quota plumbing', 'Codex Review 配额管道'],
  ['codex review quota', 'Codex Review 配额'],
  ['reverse mismatch', '反向失配'],
  ['surface 4xx errors', '展现 4xx 错误'],
  ['surface 4xx error', '展现 4xx 错误'],
  ['openai function tool strict', 'OpenAI 函数工具 strict 模式'],
  ['function tool strict', '函数工具 strict 模式'],
  ['function tool', '函数工具'],
  ['upstream fetch requests', '上游拉取请求'],
  ['upstream fetch request', '上游拉取请求'],
  ['tee stdout/stderr', '双流输出 stdout/stderr'],
  ['websocket connection pool', 'WebSocket 连接池'],
  ['connection pool', '连接池'],
  ['prompt-cache hit-rate', '提示词缓存命中率'],
  ['prompt cache hit-rate', '提示词缓存命中率'],
  ['prompt cache hit rate', '提示词缓存命中率'],
  ['hit-rate jitter', '命中率抖动'],
  ['hit rate jitter', '命中率抖动'],
  ['range hit-rate card', '区间命中率卡片'],
  ['chart panel', '图表面板'],
  ['5min granularity', '5分钟粒度'],
  ['proxy diag logs', '代理诊断日志'],
  ['proxy diag log', '代理诊断日志'],
  ['self-update', '自更新'],
  ['dirty tree', '脏工作树'],
  ['non-master branch', '非 master 分支'],
  ['empty pages', '空页面'],
  ['read tool', 'Read 工具'],
  ['effectiveconversationid', '有效会话 ID'],
  ['effective conversation id', '有效会话 ID'],
  ['effective conversation', '有效会话'],
  ['chat/gemini routes', 'Chat/Gemini 路由'],
  ['chat/gemini route', 'Chat/Gemini 路由'],
  ['ollama context metadata', 'Ollama 上下文元数据'],
  ['context metadata', '上下文元数据'],
  ['docker publish', 'Docker 发布'],
  ['latest stable tag', '最新稳定版 Tag'],
  ['stable tag', '稳定版 Tag'],
  ['stale contributor', '过期的贡献者'],
  ['checkout', '检出'],
  ['install', '安装'],
  ['stale', '过期的'],
  ['clean', '清理'],
  ['cleanup', '清理'],
  ['normalize', '规范化'],
  ['preserve', '保留'],
  ['auto-detect', '自动检测'],
  ['detect', '检测'],
  ['backfill', '回填'],
  ['propagate', '传递'],
  ['harden', '加固'],
  ['readiness', '就绪度'],
  ['surface', '展示'],
  ['honor', '遵循'],
  ['resolve', '解决'],
  ['sanitize', '消毒/净化'],
  ['refresh', '刷新'],
  ['preflight', '预检'],
  ['embeddings', '向量嵌入'],
  ['embedding', '向量嵌入'],
  ['transfer', '转移'],
  ['egress', '出口'],
  ['replays', '重放'],
  ['replay', '重放'],
  ['poisoned', '被污染的'],
  ['fingerprint', '指纹'],
  ['diagnostics', '诊断'],
  ['boundary', '边界'],
  ['collect', '收集'],
  ['exhaustion', '配额耗尽'],
  ['affinity', '亲和性'],
  ['premature', '提前的'],
  ['fallback', '回退'],
  ['resume', '恢复'],
  ['lifecycle', '生命周期'],
  ['stagger', '交错'],
  ['rate-limit', '速率限制'],
  ['streaming', '流式'],
  ['stream', '流'],
  ['direct', '直连'],
  ['setup', '初始化设置'],
  ['theme', '主题'],
  ['quarantine', '隔离'],
  ['loopback', '本地回环'],
  ['isolated', '隔离的'],
  ['reconnect', '重新连接'],
  ['allow', '允许'],
  ['popup', '弹窗'],
  ['aliases', '别名'],
  ['alias', '别名'],
  ['bridge', '网桥'],
  ['plumbing', '管道'],
  ['mismatch', '不匹配'],
  ['strict', '严格模式'],
  ['granularity', '粒度'],
  ['contributor', '贡献者'],
  ['checker', '检查器'],
  ['smoke', '冒烟测试'],
  ['manifest', '清单'],
  ['probe', '探测'],
  ['draft', '草稿'],
  ['upload', '上传'],
  ['asset', '资源'],
  ['assets', '资源'],
  ['badge', '徽章'],
  ['observability', '可观测性'],
  ['uncaught', '未捕获的'],
  ['admin', '管理员'],
  ['subprocess', '子进程'],
  ['bundle', '打包'],
  ['contract', '契约'],
  ['exhausted', '已耗尽'],
  ['warnings', '警告'],
  ['warning', '警告'],
  ['events', '事件'],
  ['event', '事件'],
  ['scheduler', '调度器'],
  ['schedule', '调度'],
  ['active', '活跃的'],
  ['expired', '已过期的'],
  ['destroy', '销毁'],
  ['diagnose', '诊断'],
  ['preference', '偏好'],
  ['concurrency', '并发'],
  ['recovery', '恢复'],
  ['transfer', '转移'],
  ['warning', '警告'],
  ['registry', '注册表'],
  ['pool', '账号池'],
  ['rotation', '轮转'],
  ['strategy', '策略'],
  ['origin', '源'],
  ['originator', '发起者'],
  ['ip', 'IP 地址'],
];

function translateText(text) {
  let result = text;

  // 1. Replace phrases and words
  for (const [english, chinese] of vocabulary) {
    const escaped = english.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'gi');
    result = result.replace(regex, chinese);
  }

  // 2. Translate leading verbs
  const verbs = [
    [/^add\b/i, '添加'],
    [/^adds\b/i, '添加'],
    [/^remove\b/i, '移除'],
    [/^removes\b/i, '移除'],
    [/^delete\b/i, '删除'],
    [/^deletes\b/i, '删除'],
    [/^update\b/i, '更新'],
    [/^updates\b/i, '更新'],
    [/^fix\b/i, '修复'],
    [/^fixes\b/i, '修复'],
    [/^implement\b/i, '实现'],
    [/^implements\b/i, '实现'],
    [/^support\b/i, '支持'],
    [/^supports\b/i, '支持'],
    [/^improve\b/i, '改进'],
    [/^improves\b/i, '改进'],
    [/^harden\b/i, '加固'],
    [/^hardens\b/i, '加固'],
    [/^prevent\b/i, '防止'],
    [/^prevents\b/i, '防止'],
    [/^avoid\b/i, '避免'],
    [/^avoids\b/i, '避免'],
    [/^handle\b/i, '处理'],
    [/^handles\b/i, '处理'],
    [/^allow\b/i, '允许'],
    [/^allows\b/i, '允许'],
    [/^clean\b/i, '清理'],
    [/^cleanup\b/i, '清理'],
    [/^normalize\b/i, '规范化'],
    [/^normalizes\b/i, '规范化'],
    [/^preserve\b/i, '保留'],
    [/^preserves\b/i, '保留'],
    [/^surface\b/i, '展示'],
    [/^surfaces\b/i, '展示'],
    [/^honor\b/i, '遵循'],
    [/^honors\b/i, '遵循'],
    [/^secure\b/i, '安全保护'],
    [/^secures\b/i, '安全保护'],
    [/^resolve\b/i, '解决'],
    [/^resolves\b/i, '解决'],
    [/^correct\b/i, '修正'],
    [/^corrects\b/i, '修正'],
    [/^propagate\b/i, '传递'],
    [/^propagates\b/i, '传递'],
    [/^optimize\b/i, '优化'],
    [/^optimizes\b/i, '优化'],
    [/^ignore\b/i, '忽略'],
    [/^ignores\b/i, '忽略'],
    [/^check\b/i, '检查'],
    [/^checks\b/i, '检查'],
    [/^align\b/i, '对齐'],
    [/^aligns\b/i, '对齐'],
    [/^clear\b/i, '清除'],
    [/^clears\b/i, '清除'],
    [/^tolerate\b/i, '兼容/容忍'],
    [/^tolerates\b/i, '兼容/容忍'],
    [/^limit\b/i, '限制'],
    [/^limits\b/i, '限制'],
    [/^setup\b/i, '设置/初始化'],
    [/^prepare\b/i, '准备'],
    [/^prepares\b/i, '准备'],
    [/^refactor\b/i, '重构'],
    [/^refactors\b/i, '重构'],
    [/^extend\b/i, '扩展'],
    [/^extends\b/i, '扩展'],
    [/^retry\b/i, '重试'],
    [/^retries\b/i, '重试'],
    [/^emit\b/i, '发送/触发'],
    [/^emits\b/i, '发送/触发'],
    [/^pin\b/i, '固定'],
    [/^pins\b/i, '固定'],
  ];

  for (const [verbRegex, chineseVerb] of verbs) {
    if (verbRegex.test(result)) {
      result = result.replace(verbRegex, chineseVerb);
      break;
    }
  }

  // 3. Common prepositions
  result = result
    .replace(/\bfor\b/gi, '用于')
    .replace(/\bto\b/gi, '到')
    .replace(/\bon\b/gi, '在')
    .replace(/\bwith\b/gi, '配合')
    .replace(/\bvia\b/gi, '通过')
    .replace(/\bby\b/gi, '通过')
    .replace(/\bin\b/gi, '在')
    .replace(/\bfrom\b/gi, '从')
    .replace(/\band\b/gi, '和');

  return result;
}

function translateCommit(line) {
  // Strip the leading '- ' first
  const hasBullet = line.startsWith('- ');
  const content = hasBullet ? line.substring(2) : line;

  const match = content.match(/^([a-zA-Z0-9_-]+)(?:\(([^)]+)\))?:\s*(.*)$/);
  if (!match) {
    return hasBullet ? `- ${translateText(content)}` : translateText(content);
  }

  const type = match[1];
  const scope = match[2];
  const subject = match[3];

  const translatedType = typeMap[type.toLowerCase()] || type;
  const translatedScope = scope ? (scopeMap[scope.toLowerCase()] || scope) : '';
  const translatedSubject = translateText(subject);

  let translatedLine = '';
  if (translatedScope) {
    translatedLine = `${translatedType}(${translatedScope})：${translatedSubject}`;
  } else {
    translatedLine = `${translatedType}：${translatedSubject}`;
  }

  return hasBullet ? `- ${translatedLine}` : translatedLine;
}

const input = fs.readFileSync(0, 'utf-8').trim();
if (!input) {
  process.exit(0);
}

// Check if it's a single phrase like "Bug fixes and improvements" or "Initial release"
const lines = input.split('\n');
if (lines.length === 1 && !lines[0].startsWith('- ')) {
  const translated = translateText(lines[0]);
  console.log(`## 🌐 English / 英文版\n${lines[0]}\n\n## 🇨🇳 中文版 (翻译)\n${translated}`);
  process.exit(0);
}

// Process multiple lines
const englishLines = [];
const chineseLines = [];

for (const line of lines) {
  englishLines.push(line);
  chineseLines.push(translateCommit(line));
}

console.log(`## 🌐 English / 英文版\n${englishLines.join('\n')}\n\n## 🇨🇳 中文版 (翻译)\n${chineseLines.join('\n')}`);
